# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00a891a2201c95420a38d4b31c33583d95fb70e453b2289f2c1b1f29927a31634024ae600ed189739100ce72c51472c679545a826613ac38f621e29fcd5ab7ac

test:
  secret_key_base: 39dfba5061adeeaa9732c7d677e4415b131c3d4b363acbaa409c303db6bc67c22f744878e304f844f7ff8631ac3f374064045eeaafefbdbdf3b913a032c7228d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
